# Classifiez automatiquement des informations

# Cellule recap

## 1. Import des modules et du dataset

In [28]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns 
import numpy as np

pd.set_option("display.max_columns", 200)

In [29]:
df_sirh = pd.read_csv("../data/raw/extrait_sirh.csv")
df_evaluation = pd.read_csv("../data/raw/extrait_eval.csv")
df_sondage = pd.read_csv("../data/raw/extrait_sondage.csv")

## 2. Analyse exploratoire

### A. SIRH

In [30]:
df_sirh.info()
display("Nombre de doublons : " + str(df_sirh.duplicated().sum()))

<class 'pandas.DataFrame'>
RangeIndex: 1470 entries, 0 to 1469
Data columns (total 12 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   id_employee                     1470 non-null   int64
 1   age                             1470 non-null   int64
 2   genre                           1470 non-null   str
 3   revenu_mensuel                  1470 non-null   int64
 4   statut_marital                  1470 non-null   str
 5   departement                     1470 non-null   str
 6   poste                           1470 non-null   str
 7   nombre_experiences_precedentes  1470 non-null   int64
 8   nombre_heures_travailless       1470 non-null   int64
 9   annee_experience_totale         1470 non-null   int64
 10  annees_dans_l_entreprise        1470 non-null   int64
 11  annees_dans_le_poste_actuel     1470 non-null   int64
dtypes: int64(8), str(4)
memory usage: 137.9 KB

'Nombre de doublons : 0'

### B. Evaluation

In [31]:
df_evaluation.info()
display("Nombre de doublons : " + str(df_evaluation.duplicated().sum()))

<class 'pandas.DataFrame'>
RangeIndex: 1470 entries, 0 to 1469
Data columns (total 10 columns):
 #   Column                                     Non-Null Count  Dtype
---  ------                                     --------------  -----
 0   satisfaction_employee_environnement        1470 non-null   int64
 1   note_evaluation_precedente                 1470 non-null   int64
 2   niveau_hierarchique_poste                  1470 non-null   int64
 3   satisfaction_employee_nature_travail       1470 non-null   int64
 4   satisfaction_employee_equipe               1470 non-null   int64
 5   satisfaction_employee_equilibre_pro_perso  1470 non-null   int64
 6   eval_number                                1470 non-null   str
 7   note_evaluation_actuelle                   1470 non-null   int64
 8   heure_supplementaires                      1470 non-null   str
 9   augementation_salaire_precedente           1470 non-null   str
dtypes: int64(7), str(3)
memory usage: 115.0 KB

'Nombre de doublons : 0'

### C. Sondage

In [32]:
df_sondage.info()
display("Nombre de doublons : " + str(df_sondage.duplicated().sum()))

<class 'pandas.DataFrame'>
RangeIndex: 1470 entries, 0 to 1469
Data columns (total 12 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   a_quitte_l_entreprise                1470 non-null   str
 1   nombre_participation_pee             1470 non-null   int64
 2   nb_formations_suivies                1470 non-null   int64
 3   nombre_employee_sous_responsabilite  1470 non-null   int64
 4   code_sondage                         1470 non-null   int64
 5   distance_domicile_travail            1470 non-null   int64
 6   niveau_education                     1470 non-null   int64
 7   domaine_etude                        1470 non-null   str
 8   ayant_enfants                        1470 non-null   str
 9   frequence_deplacement                1470 non-null   str
 10  annees_depuis_la_derniere_promotion  1470 non-null   int64
 11  annes_sous_responsable_actuel        1470 non-null   int64
dtypes: int64(8), str(4)
memory usage: 137.9 KB

'Nombre de doublons : 0'

Les features **id_employee**, **eval_number** et **code_sondage** sont potentiellement de bons candidats pour la jointure des dataframe.

In [33]:
display(df_sondage["code_sondage"].head(10))
display(df_sirh["id_employee"].head(10))
display(df_evaluation["eval_number"].head(10))

0     1
1     2
2     4
3     5
4     7
5     8
6    10
7    11
8    12
9    13
Name: code_sondage, dtype: int64

0     1
1     2
2     4
3     5
4     7
5     8
6    10
7    11
8    12
9    13
Name: id_employee, dtype: int64

0     E_1
1     E_2
2     E_4
3     E_5
4     E_7
5     E_8
6    E_10
7    E_11
8    E_12
9    E_13
Name: eval_number, dtype: str

Il semble que la distribution soit similaire. <br> En retirant **E_** de la colonne **eval_number**, on pourra procéder à notre jointure.

In [34]:
df_evaluation["eval_number"] = df_evaluation["eval_number"].apply(lambda x: int(x.replace('E_', '')))

In [35]:
df = df_sirh
df = df.merge(df_sondage, left_on="id_employee", right_on="code_sondage")
df = df.merge(df_evaluation, left_on="id_employee", right_on="eval_number")
display(df)

,id_employee,age,genre,revenu_mensuel,statut_marital,departement,poste,nombre_experiences_precedentes,nombre_heures_travailless,annee_experience_totale,annees_dans_l_entreprise,annees_dans_le_poste_actuel,a_quitte_l_entreprise,nombre_participation_pee,nb_formations_suivies,nombre_employee_sous_responsabilite,code_sondage,distance_domicile_travail,niveau_education,domaine_etude,ayant_enfants,frequence_deplacement,annees_depuis_la_derniere_promotion,annes_sous_responsable_actuel,satisfaction_employee_environnement,note_evaluation_precedente,niveau_hierarchique_poste,satisfaction_employee_nature_travail,satisfaction_employee_equipe,satisfaction_employee_equilibre_pro_perso,eval_number,note_evaluation_actuelle,heure_supplementaires,augementation_salaire_precedente
0,1,41,F,5993,Célibataire,Commercial,Cadre Commercial,8,80,8,6,4,Oui,0,0,1,1,1,2,Infra & Cloud,Y,Occasionnel,0,5,2,3,2,4,1,1,1,3,Oui,11 %
1,2,49,M,5130,Marié(e),Consulting,Assistant de Direction,1,80,10,10,7,Non,1,3,1,2,8,1,Infra & Cloud,Y,Frequent,1,7,3,2,2,2,4,3,2,4,Non,23 %
2,4,37,M,2090,Célibataire,Consulting,Consultant,6,80,7,0,0,Oui,0,3,1,4,2,2,Autre,Y,Occasionnel,0,0,4,2,1,3,2,3,4,3,Oui,15 %
3,5,33,F,2909,Marié(e),Consulting,Assistant de Direction,1,80,8,8,7,Non,0,3,1,5,3,4,Infra & Cloud,Y,Frequent,3,0,4,3,1,3,3,3,5,3,Oui,11 %
4,7,27,M,3468,Marié(e),Consulting,Consultant,9,80,6,2,2,Non,1,3,1,7,2,1,Transformation Digitale,Y,Occasionnel,2,2,1,3,1,2,4,3,7,3,Non,12 %
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1465,2061,36,M,2571,Marié(e),Consulting,Consultant,4,80,17,5,2,Non,1,3,1,2061,23,2,Transformation Digitale,Y,Frequent,0,3,3,4,2,4,3,3,2061,3,Non,17 %
1466,2062,39,M,9991,Marié(e),Consulting,Manager,4,80,9,7,7,Non,1,5,1,2062,6,1,Transformation Digitale,Y,Occasionnel,1,7,4,2,3,1,1,3,2062,3,Non,15 %
1467,2064,27,M,6142,Marié(e),Consulting,Tech Lead,1,80,6,6,2,Non,1,0,1,2064,4,3,Infra & Cloud,Y,Occasionnel,0,3,2,4,2,2,2,3,2064,4,Oui,20 %
1468,2065,49,M,5390,Marié(e),Commercial,Cadre Commercial,2,80,17,9,6,Non,0,3,1,2065,2,3,Transformation Digitale,Y,Frequent,0,8,4,2,2,2,4,2,2065,3,Non,14 %
1469,2068,34,M,4404,Marié(e),Consulting,Consultant,2,80,6,4,3,Non,0,3,1,2068,8,3,Transformation Digitale,Y,Occasionnel,1,2,2,4,2,3,1,4,2068,3,Non,12 %

Les colonnes **eval_number** et **code_sondage** font doublon de **id_employe**. <br> On peut donc les supprimer.

In [36]:
df.describe(include='all')

,id_employee,age,genre,revenu_mensuel,statut_marital,departement,poste,nombre_experiences_precedentes,nombre_heures_travailless,annee_experience_totale,annees_dans_l_entreprise,annees_dans_le_poste_actuel,a_quitte_l_entreprise,nombre_participation_pee,nb_formations_suivies,nombre_employee_sous_responsabilite,code_sondage,distance_domicile_travail,niveau_education,domaine_etude,ayant_enfants,frequence_deplacement,annees_depuis_la_derniere_promotion,annes_sous_responsable_actuel,satisfaction_employee_environnement,note_evaluation_precedente,niveau_hierarchique_poste,satisfaction_employee_nature_travail,satisfaction_employee_equipe,satisfaction_employee_equilibre_pro_perso,eval_number,note_evaluation_actuelle,heure_supplementaires,augementation_salaire_precedente
count,1470.000000,1470.000000,1470,1470.000000,1470,1470,1470,1470.000000,1470.0,1470.000000,1470.000000,1470.000000,1470,1470.000000,1470.000000,1470.0,1470.000000,1470.000000,1470.000000,1470,1470,1470,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470,1470
unique,NaN,NaN,2,NaN,3,3,9,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,6,1,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,15
top,NaN,NaN,M,NaN,Marié(e),Consulting,Cadre Commercial,NaN,NaN,NaN,NaN,NaN,Non,NaN,NaN,NaN,NaN,NaN,NaN,Infra & Cloud,Y,Occasionnel,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Non,11 %
freq,NaN,NaN,882,NaN,673,961,326,NaN,NaN,NaN,NaN,NaN,1233,NaN,NaN,NaN,NaN,NaN,NaN,606,1470,1043,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1054,210
mean,1024.865306,36.923810,NaN,6502.931293,NaN,NaN,NaN,2.693197,80.0,11.279592,7.008163,4.229252,NaN,0.793878,2.799320,1.0,1024.865306,9.192517,2.912925,NaN,NaN,NaN,2.187755,4.123129,2.721769,2.729932,2.063946,2.728571,2.712245,2.761224,1024.865306,3.153741,NaN,NaN
std,602.024335,9.135373,NaN,4707.956783,NaN,NaN,NaN,2.498009,0.0,7.780782,6.126525,3.623137,NaN,0.852077,1.289271,0.0,602.024335,8.106864,1.024165,NaN,NaN,NaN,3.222430,3.568136,1.093082,0.711561,1.106940,1.102846,1.081209,0.706476,602.024335,0.360824,NaN,NaN
min,1.000000,18.000000,NaN,1009.000000,NaN,NaN,NaN,0.000000,80.0,0.000000,0.000000,0.000000,NaN,0.000000,0.000000,1.0,1.000000,1.000000,1.000000,NaN,NaN,NaN,0.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,3.000000,NaN,NaN
25%,491.250000,30.000000,NaN,2911.000000,NaN,NaN,NaN,1.000000,80.0,6.000000,3.000000,2.000000,NaN,0.000000,2.000000,1.0,491.250000,2.000000,2.000000,NaN,NaN,NaN,0.000000,2.000000,2.000000,2.000000,1.000000,2.000000,2.000000,2.000000,491.250000,3.000000,NaN,NaN
50%,1020.500000,36.000000,NaN,4919.000000,NaN,NaN,NaN,2.000000,80.0,10.000000,5.000000,3.000000,NaN,1.000000,3.000000,1.0,1020.500000,7.000000,3.000000,NaN,NaN,NaN,1.000000,3.000000,3.000000,3.000000,2.000000,3.000000,3.000000,3.000000,1020.500000,3.000000,NaN,NaN
75%,1555.750000,43.000000,NaN,8379.000000,NaN,NaN,NaN,4.000000,80.0,15.000000,9.000000,7.000000,NaN,1.000000,3.000000,1.0,1555.750000,14.000000,4.000000,NaN,NaN,NaN,3.000000,7.000000,4.000000,3.000000,3.000000,4.000000,4.000000,3.000000,1555.750000,3.000000,NaN,NaN
max,2068.000000,60.000000,NaN,19999.000000,NaN,NaN,NaN,9.000000,80.0,40.000000,40.000000,18.000000,NaN,3.000000,6.000000,1.0,2068.000000,29.000000,5.000000,NaN,NaN,NaN,15.000000,17.000000,4.000000,4.000000,5.000000,4.000000,4.000000,4.000000,2068.000000,4.000000,NaN,NaN

Les colonnes **eval_number** et **code_sondage** font doublon de **id_employe**. describe() montre bien que leur distribution est identique <br> On peut donc les supprimer.

In [37]:
df = df.drop(["eval_number", "code_sondage"], axis=1)

In [38]:
df["poste"].value_counts()

poste
Cadre Commercial           326
Assistant de Direction     292
Consultant                 259
Tech Lead                  145
Manager                    131
Senior Manager             102
Représentant Commercial     83
Directeur Technique         80
Ressources Humaines         52
Name: count, dtype: int64